### ISSUE TITLE
SDK location not found. Define location with sdk.dir in the local.properties

### ISSUE THREAD

**Issue by w3farid** [smaho-gmbh/android_wifi_info#4]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android_wifi_info'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by vincevargadev** [comment]
Thank you @w3farid for raising the issue. Can you verify that it's an issue with the `android_wifi_info` plugin and not your local Flutter+Android Studio configuration? Can you run other projects? In which folder did you try to run the project?

Could you execute `flutter doctor` and share the results?

Could you check this question? https://stackoverflow.com/questions/27620262/sdk-location-not-found-define-location-with-sdk-dir-in-the-local-properties-fil

**Comment by w3farid** [comment]
@vargavince91 thanks for reply. I have solved, just  select sdk from File>Project Structure> project to select android sdk

**Comment by livingstonex** [comment]
please, @w3farid what did you do to resolve this issue? I don't get what you mean by this: File>Project Structure> project to select android sdk

**Comment by 78sarmad** [comment]
> please, @w3farid what did you do to resolve this issue? I don't get what you mean by this: File>Project Structure> project to select android sdk

Open Android Studio, go to File menu and select File Structure and specify an SDK with compileSdkVersion or targetSdkVersion that you defined in the "app/build.gradle" file.

**Comment by snjjay** [comment]
While writing a programme or setting up a project, there may be a lot of errors in the code. For example, the path to the project's local.properties file is not set.
The file Local.properties is missing from the project folder, and your sdk path is not configured in an environment variable.
This error message can also be caused by several lines in the local.properties file.   Refer to https://kodlogs.net/330/sdk-location-not-found-define-location-with-sdk-dir-in-the-local-properties#why
